"""Initial Migration

Revision ID: e5c6e71f62a6
Revises: 
Create Date: 2022-03-06 08:11:56.169361

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'e5c6e71f62a6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('receiptsummary', sa.Column('other_data', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('receiptsummary', 'other_data')
    # ### end Alembic commands ###
